// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWlSsjpgQN4E_Bt3esMa1hIFJ9nESAEmA',
    appId: '1:359335119695:web:8dc0ac66d6a874ddcb533a',
    messagingSenderId: '359335119695',
    projectId: 'tradeflash-l2966',
    authDomain: 'tradeflash-l2966.firebaseapp.com',
    storageBucket: 'tradeflash-l2966.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWlSsjpgQN4E_Bt3esMa1hIFJ9nESAEmA',
    appId: '1:359335119695:android:b61cd1e2245350dfcb533a',
    messagingSenderId: '359335119695',
    projectId: 'tradeflash-l2966',
    storageBucket: 'tradeflash-l2966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhbcUe2s1B-K_qd4w3fmyKef0AQhJtNAg',
    appId: '1:359335119695:ios:08a76755006c0b6ccb533a',
    messagingSenderId: '359335119695',
    projectId: 'tradeflash-l2966',
    storageBucket: 'tradeflash-l2966.firebasestorage.app',
    androidClientId:
        '359335119695-llosj38fvsae11cnts31bdhsoef3iiud.apps.googleusercontent.com',
    iosClientId:
        '359335119695-653anqm8bnhco0oqlqrmdrc09aeei2s9.apps.googleusercontent.com',
    iosBundleId: 'com.emerge.emergeApp',
  );
}
