import 'package:emerge_app/core/theme/archetype_theme.dart';
import 'package:emerge_app/features/auth/domain/entities/user_extension.dart';
import 'package:emerge_app/features/habits/domain/entities/habit.dart';
import 'package:emerge_app/features/world_map/domain/models/archetype_map_config.dart';
import 'package:emerge_app/features/world_map/domain/models/world_node.dart';
import 'package:emerge_app/features/world_map/domain/models/hex_location.dart';
import 'package:flutter/material.dart';

/// Catalog of all archetype-specific world maps
class ArchetypeMapsCatalog {
  /// Get the map configuration for a specific archetype
  static ArchetypeMapConfig getMapForArchetype(UserArchetype archetype) {
    switch (archetype) {
      case UserArchetype.athlete:
        return _athleteMap;
      case UserArchetype.scholar:
        return _scholarMap;
      case UserArchetype.creator:
        return _creatorMap;
      case UserArchetype.stoic:
        return _stoicMap;
      case UserArchetype.zealot:
        return _zealotMap;
      case UserArchetype.none:
        return _explorerMap;
    }
  }

  // ============ ATHLETE MAP: Summit Peak ============
  static final _athleteMap = ArchetypeMapConfig(
    archetype: UserArchetype.athlete,
    mapName: 'Summit Peak',
    mapDescription: 'Climb the mountain of physical mastery',
    primaryColor: ArchetypeTheme.forArchetype(UserArchetype.athlete).primaryColor,
    accentColor: ArchetypeTheme.forArchetype(UserArchetype.athlete).accentColor,
    backgroundGradient: ArchetypeTheme.forArchetype(UserArchetype.athlete).backgroundGradient,
    journeyIcon: Icons.hiking,
    nodes: [
      // STAGE 1: VALLEY BASE (Levels 1-5)
      WorldNode(
        id: 'ath_1_1',
        name: 'First Steps',
        description: 'Begin your athletic journey',
        directive:
            'Establish your rhythm: Complete 3 workouts this week to build foundational energy.',
        emoji: '⛺',
        targetedAttributes: [HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.vitality: 10},
        requiredLevel: 1,
        stage: 1,
        levelInStage: 1,
        archetype: 'athlete',
        primaryAttributes: ['strength'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, 0),
        position: const Offset(0.5, 0.05),
        connectedNodeIds: ['ath_1_2'],
        state: NodeState.available,
      ),
      WorldNode(
        id: 'ath_1_2',
        name: 'Foundation',
        description: 'Build your base',
        directive:
            'Focus on form: Complete a core strength or mobility session today.',
        emoji: '🥾',
        targetedAttributes: [HabitAttribute.vitality, HabitAttribute.strength],
        xpBoosts: {HabitAttribute.vitality: 12, HabitAttribute.strength: 8},
        requiredLevel: 2,
        stage: 1,
        levelInStage: 2,
        archetype: 'athlete',
        primaryAttributes: ['strength', 'vitality'],
        type: NodeType.resource,
        hexLocation: const HexLocation(0, -1),
        position: const Offset(0.35, 0.12),
        connectedNodeIds: ['ath_1_3'],
      ),
      WorldNode(
        id: 'ath_1_3',
        name: 'Strength Trial',
        description: 'Test your power',
        directive:
            'Push limits: Perform a progressive overload strength training session.',
        emoji: '🪨',
        targetedAttributes: [HabitAttribute.strength],
        xpBoosts: {HabitAttribute.strength: 15},
        requiredLevel: 3,
        stage: 1,
        levelInStage: 3,
        archetype: 'athlete',
        primaryAttributes: ['strength'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(-1, -1),
        position: const Offset(0.2, 0.18),
        connectedNodeIds: ['ath_1_4'],
      ),
      WorldNode(
        id: 'ath_1_4',
        name: 'Endurance Build',
        description: 'Test your stamina',
        directive:
            'Build the engine: Run, cycle, or swim continuously for 30 minutes.',
        emoji: '🏃',
        targetedAttributes: [HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.vitality: 15},
        requiredLevel: 4,
        stage: 1,
        levelInStage: 4,
        archetype: 'athlete',
        primaryAttributes: ['vitality'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -1),
        position: const Offset(0.65, 0.15),
        connectedNodeIds: ['ath_1_5'],
      ),
      WorldNode(
        id: 'ath_1_5',
        name: 'Valley Gate',
        description: 'Complete Stage 1',
        directive:
            'The Trial: Complete a high-intensity interval (HIIT) session to prove your readiness.',
        emoji: '⛩️',
        targetedAttributes: [HabitAttribute.vitality, HabitAttribute.strength],
        xpBoosts: {HabitAttribute.vitality: 25, HabitAttribute.strength: 25},
        requiredLevel: 5,
        stage: 1,
        levelInStage: 5,
        archetype: 'athlete',
        primaryAttributes: ['strength', 'vitality'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -2),
        position: const Offset(0.5, 0.22),
        connectedNodeIds: ['ath_2_1'],
      ),
      // STAGE 2: FOREST PATH (Levels 6-10)
      WorldNode(
        id: 'ath_2_1',
        name: 'Forest Entry',
        description: 'Enter the wild',
        directive: 'A moment of clarity: Practice mindful movement today.',
        emoji: '🌲',
        targetedAttributes: [HabitAttribute.focus],
        xpBoosts: {HabitAttribute.focus: 15},
        requiredLevel: 6,
        stage: 2,
        levelInStage: 1,
        archetype: 'athlete',
        primaryAttributes: ['focus'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, -3),
        position: const Offset(0.5, 0.30),
        connectedNodeIds: ['ath_2_2'],
      ),
      WorldNode(
        id: 'ath_2_2',
        name: 'Runner\'s Grove',
        description: 'Where speed is born',
        directive: 'Build endurance: Run for 20 minutes at steady pace.',
        emoji: '🌿',
        targetedAttributes: [HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.vitality: 20},
        requiredLevel: 7,
        stage: 2,
        levelInStage: 2,
        archetype: 'athlete',
        primaryAttributes: ['vitality'],
        type: NodeType.resource,
        hexLocation: const HexLocation(-1, -3),
        position: const Offset(0.3, 0.36),
        connectedNodeIds: ['ath_2_3'],
      ),
      WorldNode(
        id: 'ath_2_3',
        name: 'Warrior\'s Trial',
        description: 'Test your limits',
        directive: 'Strength test: Complete 5 sets of your hardest exercise.',
        emoji: '⚔️',
        targetedAttributes: [HabitAttribute.strength],
        xpBoosts: {HabitAttribute.strength: 25},
        requiredLevel: 8,
        stage: 2,
        levelInStage: 3,
        archetype: 'athlete',
        primaryAttributes: ['strength'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(0, -4),
        position: const Offset(0.5, 0.38),
        connectedNodeIds: ['ath_2_4'],
      ),
      WorldNode(
        id: 'ath_2_4',
        name: 'Stamina Climb',
        description: 'Build your engine',
        directive: 'Cardio push: 30 minutes of continuous cardiovascular exercise.',
        emoji: '⛰️',
        targetedAttributes: [HabitAttribute.vitality, HabitAttribute.strength],
        xpBoosts: {HabitAttribute.vitality: 22, HabitAttribute.strength: 15},
        requiredLevel: 9,
        stage: 2,
        levelInStage: 4,
        archetype: 'athlete',
        primaryAttributes: ['vitality', 'strength'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -3),
        position: const Offset(0.7, 0.38),
        connectedNodeIds: ['ath_2_5'],
      ),
      WorldNode(
        id: 'ath_2_5',
        name: 'Forest Master',
        description: 'Complete Stage 2',
        directive: 'The Trial: Complete a triathlon-style workout (cardio + strength + endurance).',
        emoji: '🏆',
        targetedAttributes: [
          HabitAttribute.vitality,
          HabitAttribute.strength,
          HabitAttribute.focus,
        ],
        xpBoosts: {
          HabitAttribute.vitality: 35,
          HabitAttribute.strength: 35,
          HabitAttribute.focus: 25,
        },
        requiredLevel: 10,
        stage: 2,
        levelInStage: 5,
        archetype: 'athlete',
        primaryAttributes: ['strength', 'vitality', 'focus'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -5),
        position: const Offset(0.5, 0.45),
        connectedNodeIds: ['ath_3_1'],
      ),

      // STAGE 3: MOUNTAIN ASCENT (Levels 11-15)
      WorldNode(
        id: 'ath_3_1',
        name: 'Mountain Base',
        description: 'The climb begins',
        directive: 'Summit mindset: Visualize your athletic goals.',
        emoji: '🏔️',
        targetedAttributes: [HabitAttribute.focus],
        xpBoosts: {HabitAttribute.focus: 20},
        requiredLevel: 11,
        stage: 3,
        levelInStage: 1,
        archetype: 'athlete',
        primaryAttributes: ['focus'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, -6),
        position: const Offset(0.5, 0.52),
        connectedNodeIds: ['ath_3_2'],
      ),
      WorldNode(
        id: 'ath_3_2',
        name: 'Peak Conditioning',
        description: 'Elite level training',
        directive: 'Elite fitness: 45 minutes of high-intensity training.',
        emoji: '💪',
        targetedAttributes: [HabitAttribute.vitality, HabitAttribute.strength],
        xpBoosts: {HabitAttribute.vitality: 30, HabitAttribute.strength: 30},
        requiredLevel: 12,
        stage: 3,
        levelInStage: 2,
        archetype: 'athlete',
        primaryAttributes: ['vitality', 'strength'],
        type: NodeType.resource,
        hexLocation: const HexLocation(-1, -6),
        position: const Offset(0.3, 0.58),
        connectedNodeIds: ['ath_3_3'],
      ),
      WorldNode(
        id: 'ath_3_3',
        name: 'Iron Will',
        description: 'Push beyond limits',
        directive: '极限 test: Complete your most difficult workout to failure.',
        emoji: '🔥',
        targetedAttributes: [HabitAttribute.strength, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.strength: 35, HabitAttribute.focus: 30},
        requiredLevel: 13,
        stage: 3,
        levelInStage: 3,
        archetype: 'athlete',
        primaryAttributes: ['strength', 'focus'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(0, -7),
        position: const Offset(0.5, 0.60),
        connectedNodeIds: ['ath_3_4'],
      ),
      WorldNode(
        id: 'ath_3_4',
        name: 'Altitude Training',
        description: 'Adapt and overcome',
        directive: 'Breath work: Combine cardio with breath control exercises.',
        emoji: '🌬️',
        targetedAttributes: [HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.vitality: 35},
        requiredLevel: 14,
        stage: 3,
        levelInStage: 4,
        archetype: 'athlete',
        primaryAttributes: ['vitality'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -6),
        position: const Offset(0.7, 0.58),
        connectedNodeIds: ['ath_3_5'],
      ),
      WorldNode(
        id: 'ath_3_5',
        name: 'Summit Master',
        description: 'Complete Stage 3 - You are legendary',
        directive: 'The Final Trial: Design and complete your ultimate fitness challenge.',
        emoji: '🏔️',
        targetedAttributes: [
          HabitAttribute.vitality,
          HabitAttribute.strength,
          HabitAttribute.focus,
        ],
        xpBoosts: {
          HabitAttribute.vitality: 50,
          HabitAttribute.strength: 50,
          HabitAttribute.focus: 40,
        },
        requiredLevel: 15,
        stage: 3,
        levelInStage: 5,
        archetype: 'athlete',
        primaryAttributes: ['strength', 'vitality', 'focus'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -8),
        position: const Offset(0.5, 0.68),
        connectedNodeIds: [],
      ),
    ],
  );

  // ============ SCHOLAR MAP: Knowledge Nexus ============
  static final _scholarMap = ArchetypeMapConfig(
    archetype: UserArchetype.scholar,
    mapName: 'Knowledge Nexus',
    mapDescription: 'Ascend the tower of wisdom',
    primaryColor: ArchetypeTheme.forArchetype(UserArchetype.scholar).primaryColor,
    accentColor: ArchetypeTheme.forArchetype(UserArchetype.scholar).accentColor,
    backgroundGradient: ArchetypeTheme.forArchetype(UserArchetype.scholar).backgroundGradient,
    journeyIcon: Icons.auto_stories,
    nodes: [
      // STAGE 1: LIBRARY (Levels 1-5)
      WorldNode(
        id: 'sch_1_1',
        name: 'Library Entrance',
        description: 'The journey of knowledge begins',
        directive:
            'Gather knowledge: Read 10 pages of a non-fiction book or listen to an educational podcast.',
        emoji: '🏛️',
        targetedAttributes: [HabitAttribute.intellect],
        xpBoosts: {HabitAttribute.intellect: 10},
        requiredLevel: 1,
        stage: 1,
        levelInStage: 1,
        archetype: 'scholar',
        primaryAttributes: ['intellect'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, 0),
        position: const Offset(0.5, 0.05),
        connectedNodeIds: ['sch_1_2'],
        state: NodeState.available,
      ),
      WorldNode(
        id: 'sch_1_2',
        name: 'Reading Nook',
        description: 'Absorb ancient wisdom',
        directive:
            'Deep work: Complete a 30-minute undistracted focused learning session.',
        emoji: '📚',
        targetedAttributes: [HabitAttribute.intellect, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.intellect: 12, HabitAttribute.focus: 10},
        requiredLevel: 2,
        stage: 1,
        levelInStage: 2,
        archetype: 'scholar',
        primaryAttributes: ['intellect', 'focus'],
        type: NodeType.resource,
        hexLocation: const HexLocation(0, -1),
        position: const Offset(0.4, 0.12),
        connectedNodeIds: ['sch_1_3'],
      ),
      WorldNode(
        id: 'sch_1_3',
        name: 'Focus Trial',
        description: 'Test your concentration',
        directive:
            'Clear the noise: Meditate or practice stillness for 20 minutes to train your focus.',
        emoji: '🧘',
        targetedAttributes: [HabitAttribute.focus],
        xpBoosts: {HabitAttribute.focus: 18},
        requiredLevel: 3,
        stage: 1,
        levelInStage: 3,
        archetype: 'scholar',
        primaryAttributes: ['focus'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(-1, -1),
        position: const Offset(0.25, 0.18),
        connectedNodeIds: ['sch_1_4'],
      ),
      WorldNode(
        id: 'sch_1_4',
        name: 'Idea Lab',
        description: 'Experiment and discover',
        directive:
            'Lateral thinking: Brainstorm 5 new ideas or solve a complex puzzle.',
        emoji: '⚗️',
        targetedAttributes: [
          HabitAttribute.intellect,
          HabitAttribute.creativity,
        ],
        xpBoosts: {HabitAttribute.intellect: 15, HabitAttribute.creativity: 10},
        requiredLevel: 4,
        stage: 1,
        levelInStage: 4,
        archetype: 'scholar',
        primaryAttributes: ['intellect', 'creativity'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -1),
        position: const Offset(0.65, 0.16),
        connectedNodeIds: ['sch_1_5'],
      ),
      WorldNode(
        id: 'sch_1_5',
        name: 'First Revelation',
        description: 'Your first breakthrough',
        directive:
            'The Trial: Write a summary or journal entry about your key learnings this week.',
        emoji: '💡',
        targetedAttributes: [HabitAttribute.intellect, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.intellect: 30, HabitAttribute.focus: 25},
        requiredLevel: 5,
        stage: 1,
        levelInStage: 5,
        archetype: 'scholar',
        primaryAttributes: ['intellect', 'focus'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -2),
        position: const Offset(0.5, 0.24),
        connectedNodeIds: ['sch_2_1'],
      ),
    ],
  );

  // ============ CREATOR MAP: Forge Garden ============
  static final _creatorMap = ArchetypeMapConfig(
    archetype: UserArchetype.creator,
    mapName: 'Forge Garden',
    mapDescription: 'Cultivate your creative spirit',
    primaryColor: ArchetypeTheme.forArchetype(UserArchetype.creator).primaryColor,
    accentColor: ArchetypeTheme.forArchetype(UserArchetype.creator).accentColor,
    backgroundGradient: ArchetypeTheme.forArchetype(UserArchetype.creator).backgroundGradient,
    journeyIcon: Icons.brush,
    nodes: [
      // STAGE 1: INSPIRATION GARDEN (Levels 1-5)
      WorldNode(
        id: 'cre_1_1',
        name: 'Inspiration Spring',
        description: 'Where ideas are born',
        directive:
            'Free creation: Spend 20 minutes creating something without judgment.',
        emoji: '⛲',
        targetedAttributes: [HabitAttribute.creativity],
        xpBoosts: {HabitAttribute.creativity: 15},
        requiredLevel: 1,
        stage: 1,
        levelInStage: 1,
        archetype: 'creator',
        primaryAttributes: ['creativity'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, 0),
        position: const Offset(0.5, 0.05),
        connectedNodeIds: ['cre_1_2'],
        state: NodeState.available,
      ),
      WorldNode(
        id: 'cre_1_2',
        name: 'Sketch Meadow',
        description: 'Practice your craft',
        directive:
            'Refine your craft: Focus on a single creative task for 30 uninterrupted minutes.',
        emoji: '📝',
        targetedAttributes: [HabitAttribute.creativity, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.creativity: 12, HabitAttribute.focus: 8},
        requiredLevel: 2,
        stage: 1,
        levelInStage: 2,
        archetype: 'creator',
        primaryAttributes: ['creativity', 'focus'],
        type: NodeType.resource,
        hexLocation: const HexLocation(0, -1),
        position: const Offset(0.4, 0.12),
        connectedNodeIds: ['cre_1_3'],
      ),
      WorldNode(
        id: 'cre_1_3',
        name: 'Creative Trial',
        description: 'Push through blocks',
        directive:
            'Creation under pressure: Create something when you feel uninspired.',
        emoji: '🎨',
        targetedAttributes: [HabitAttribute.creativity],
        xpBoosts: {HabitAttribute.creativity: 20},
        requiredLevel: 3,
        stage: 1,
        levelInStage: 3,
        archetype: 'creator',
        primaryAttributes: ['creativity'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(-1, -1),
        position: const Offset(0.25, 0.18),
        connectedNodeIds: ['cre_1_4'],
      ),
      WorldNode(
        id: 'cre_1_4',
        name: 'Master Study',
        description: 'Learn from the best',
        directive:
            'Draw inspiration: Study the work of a master in your field.',
        emoji: '🖼️',
        targetedAttributes: [HabitAttribute.intellect, HabitAttribute.creativity],
        xpBoosts: {HabitAttribute.intellect: 12, HabitAttribute.creativity: 15},
        requiredLevel: 4,
        stage: 1,
        levelInStage: 4,
        archetype: 'creator',
        primaryAttributes: ['creativity', 'intellect'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -1),
        position: const Offset(0.65, 0.15),
        connectedNodeIds: ['cre_1_5'],
      ),
      WorldNode(
        id: 'cre_1_5',
        name: 'First Masterpiece',
        description: 'Complete Stage 1',
        directive:
            'The Trial: Publish or share your recent creation with someone today.',
        emoji: '🖼️',
        targetedAttributes: [
          HabitAttribute.creativity,
          HabitAttribute.strength,
        ],
        xpBoosts: {HabitAttribute.creativity: 35, HabitAttribute.strength: 20},
        requiredLevel: 5,
        stage: 1,
        levelInStage: 5,
        archetype: 'creator',
        primaryAttributes: ['creativity', 'vitality'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -2),
        position: const Offset(0.5, 0.24),
        connectedNodeIds: ['cre_2_1'],
      ),
    ],
  );

  // ============ STOIC MAP: Ancient Path ============
  static final _stoicMap = ArchetypeMapConfig(
    archetype: UserArchetype.stoic,
    mapName: 'Ancient Path',
    mapDescription: 'Walk the way of wisdom and discipline',
    primaryColor: ArchetypeTheme.forArchetype(UserArchetype.stoic).primaryColor,
    accentColor: ArchetypeTheme.forArchetype(UserArchetype.stoic).accentColor,
    backgroundGradient: ArchetypeTheme.forArchetype(UserArchetype.stoic).backgroundGradient,
    journeyIcon: Icons.self_improvement,
    nodes: [
      // STAGE 1: TEMPLE ENTRY (Levels 1-5)
      WorldNode(
        id: 'sto_1_1',
        name: 'Stone Gate',
        description: 'Enter the path of discipline',
        directive:
            'Voluntary discomfort: Take a cold shower or lean into physical discomfort today.',
        emoji: '⛩️',
        targetedAttributes: [HabitAttribute.strength],
        xpBoosts: {HabitAttribute.strength: 12},
        requiredLevel: 1,
        stage: 1,
        levelInStage: 1,
        archetype: 'stoic',
        primaryAttributes: ['focus', 'spirit'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, 0),
        position: const Offset(0.5, 0.05),
        connectedNodeIds: ['sto_1_2'],
        state: NodeState.available,
      ),
      WorldNode(
        id: 'sto_1_2',
        name: 'Meditation Garden',
        description: 'Find inner peace',
        directive:
            'Stillness: Practice 15 minutes of mindfulness without moving.',
        emoji: '🎋',
        targetedAttributes: [HabitAttribute.focus, HabitAttribute.spirit],
        xpBoosts: {HabitAttribute.focus: 15, HabitAttribute.spirit: 10},
        requiredLevel: 2,
        stage: 1,
        levelInStage: 2,
        archetype: 'stoic',
        primaryAttributes: ['focus', 'spirit'],
        type: NodeType.resource,
        hexLocation: const HexLocation(0, -1),
        position: const Offset(0.45, 0.12),
        connectedNodeIds: ['sto_1_3'],
      ),
      WorldNode(
        id: 'sto_1_3',
        name: 'Will Trial',
        description: 'Test your resolve',
        directive:
            'Self-examination: Journal what is in your control and what is not.',
        emoji: '💧',
        targetedAttributes: [HabitAttribute.focus],
        xpBoosts: {HabitAttribute.focus: 18},
        requiredLevel: 3,
        stage: 1,
        levelInStage: 3,
        archetype: 'stoic',
        primaryAttributes: ['focus'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(-1, -1),
        position: const Offset(0.25, 0.20),
        connectedNodeIds: ['sto_1_4'],
      ),
      WorldNode(
        id: 'sto_1_4',
        name: 'Fortitude Build',
        description: 'Build your endurance',
        directive:
            'Physical fortitude: Hold a plank for 2 minutes or perform an isometric hold.',
        emoji: '🌋',
        targetedAttributes: [HabitAttribute.strength, HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.strength: 15, HabitAttribute.vitality: 10},
        requiredLevel: 4,
        stage: 1,
        levelInStage: 4,
        archetype: 'stoic',
        primaryAttributes: ['strength'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -1),
        position: const Offset(0.7, 0.18),
        connectedNodeIds: ['sto_1_5'],
      ),
      WorldNode(
        id: 'sto_1_5',
        name: 'First Awakening',
        description: 'Complete Stage 1',
        directive:
            'The Trial: Fast from a common comfort (e.g., social media, sugar) for 24 hours.',
        emoji: '👁️',
        targetedAttributes: [HabitAttribute.strength, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.strength: 30, HabitAttribute.focus: 25},
        requiredLevel: 5,
        stage: 1,
        levelInStage: 5,
        archetype: 'stoic',
        primaryAttributes: ['focus', 'spirit'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -2),
        position: const Offset(0.5, 0.26),
        connectedNodeIds: ['sto_2_1'],
      ),
    ],
  );

  // ============ ZEALOT MAP: Sacred Peak ============
  static final _zealotMap = ArchetypeMapConfig(
    archetype: UserArchetype.zealot,
    mapName: 'Ethereal Realm',
    mapDescription: 'Transcend the ordinary',
    primaryColor: ArchetypeTheme.forArchetype(UserArchetype.zealot).primaryColor,
    accentColor: ArchetypeTheme.forArchetype(UserArchetype.zealot).accentColor,
    backgroundGradient: ArchetypeTheme.forArchetype(UserArchetype.zealot).backgroundGradient,
    journeyIcon: Icons.auto_awesome,
    nodes: [
      WorldNode(
        id: 'mys_1',
        name: 'Spirit Portal',
        description: 'Enter the ethereal realm',
        directive:
            'Open your mind: Dedicate 10 minutes to unguided meditation or free association.',
        emoji: '🌀',
        targetedAttributes: [HabitAttribute.focus, HabitAttribute.creativity],
        xpBoosts: {HabitAttribute.focus: 10, HabitAttribute.creativity: 10},
        requiredLevel: 1,
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, 0),
        position: const Offset(0.5, 0.05),
        connectedNodeIds: ['mys_2'],
        state: NodeState.available,
      ),
      WorldNode(
        id: 'mys_2',
        name: 'Dream Garden',
        description: 'Where visions bloom',
        directive:
            'Dream logic: Keep a dream journal or write down your first thought upon waking.',
        emoji: '🌌',
        targetedAttributes: [HabitAttribute.creativity],
        xpBoosts: {HabitAttribute.creativity: 15},
        requiredLevel: 2,
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, -1),
        position: const Offset(0.4, 0.12),
        connectedNodeIds: ['mys_3', 'mys_4'],
      ),
      WorldNode(
        id: 'mys_3',
        name: 'Cosmic Well',
        description: 'Draw from infinite energy',
        directive:
            'Energy flow: Practice breathwork, qigong, or yoga for 15 minutes.',
        emoji: '✨',
        targetedAttributes: [HabitAttribute.vitality, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.vitality: 12, HabitAttribute.focus: 15},
        requiredLevel: 3,
        type: NodeType.resource,
        hexLocation: const HexLocation(-1, -1),
        position: const Offset(0.25, 0.19),
        connectedNodeIds: ['mys_5'],
      ),
      WorldNode(
        id: 'mys_4',
        name: 'Astral Bridge',
        description: 'Connect to higher wisdom',
        directive:
            'Esoteric study: Read about a philosophical or spiritual concept new to you.',
        emoji: '🌉',
        targetedAttributes: [HabitAttribute.intellect, HabitAttribute.focus],
        xpBoosts: {HabitAttribute.intellect: 12, HabitAttribute.focus: 12},
        requiredLevel: 4,
        type: NodeType.waypoint,
        hexLocation: const HexLocation(1, -1),
        position: const Offset(0.68, 0.16),
        connectedNodeIds: ['mys_5'],
      ),
      WorldNode(
        id: 'mys_5',
        name: 'First Transcendence',
        description: 'You glimpse beyond',
        directive:
            'The Trial: Spend a full hour in complete silence, simply observing your thoughts.',
        emoji: '🧿',
        targetedAttributes: [
          HabitAttribute.focus,
          HabitAttribute.creativity,
          HabitAttribute.intellect,
        ],
        xpBoosts: {
          HabitAttribute.focus: 25,
          HabitAttribute.creativity: 25,
          HabitAttribute.intellect: 20,
        },
        requiredLevel: 5,
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -2),
        position: const Offset(0.5, 0.25),
        connectedNodeIds: ['mys_6'],
      ),
    ],
  );

  // ============ EXPLORER MAP (Default/None) ============
  static final _explorerMap = ArchetypeMapConfig(
    archetype: UserArchetype.none,
    mapName: 'Explorer\'s Journey',
    mapDescription: 'Discover your path',
    primaryColor: ArchetypeTheme.forArchetype(UserArchetype.none).primaryColor,
    accentColor: ArchetypeTheme.forArchetype(UserArchetype.none).accentColor,
    backgroundGradient: ArchetypeTheme.forArchetype(UserArchetype.none).backgroundGradient,
    journeyIcon: Icons.explore,
    nodes: [
      // STAGE 1: UNKNOWN PATH (Levels 1-5)
      WorldNode(
        id: 'exp_1_1',
        name: 'Starting Point',
        description: 'Every journey begins with a single step',
        directive: 'Take action: Complete your first habit in any category.',
        emoji: '📍',
        targetedAttributes: [HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.vitality: 10},
        requiredLevel: 1,
        stage: 1,
        levelInStage: 1,
        archetype: 'explorer',
        primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
        type: NodeType.waypoint,
        hexLocation: const HexLocation(0, 0),
        position: const Offset(0.5, 0.05),
        connectedNodeIds: ['exp_1_2'],
        state: NodeState.available,
      ),
      WorldNode(
        id: 'exp_1_2',
        name: 'First Crossroads',
        description: 'Choose your direction',
        directive: 'Explore: Try habits from two different attribute categories.',
        emoji: '🛤️',
        targetedAttributes: [HabitAttribute.focus, HabitAttribute.strength],
        xpBoosts: {HabitAttribute.focus: 10, HabitAttribute.strength: 10},
        requiredLevel: 2,
        stage: 1,
        levelInStage: 2,
        archetype: 'explorer',
        primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
        type: NodeType.resource,
        hexLocation: const HexLocation(0, -1),
        position: const Offset(0.45, 0.12),
        connectedNodeIds: ['exp_1_3'],
      ),
      WorldNode(
        id: 'exp_1_3',
        name: 'Discovery Trial',
        description: 'Test your versatility',
        directive: 'Variety: Complete 3 different types of habits in one day.',
        emoji: '🔭',
        targetedAttributes: [HabitAttribute.intellect, HabitAttribute.creativity],
        xpBoosts: {HabitAttribute.intellect: 15, HabitAttribute.creativity: 15},
        requiredLevel: 3,
        stage: 1,
        levelInStage: 3,
        archetype: 'explorer',
        primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
        type: NodeType.challenge,
        hexLocation: const HexLocation(-1, -1),
        position: const Offset(0.3, 0.18),
        connectedNodeIds: ['exp_1_4'],
      ),
      WorldNode(
        id: 'exp_1_4',
        name: 'Creative Oasis',
        description: 'Express yourself',
        directive: 'Create: Spend time on a creative or learning activity.',
        emoji: '🌴',
        targetedAttributes: [HabitAttribute.creativity, HabitAttribute.vitality],
        xpBoosts: {HabitAttribute.creativity: 15, HabitAttribute.vitality: 10},
        requiredLevel: 4,
        stage: 1,
        levelInStage: 4,
        archetype: 'explorer',
        primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
        type: NodeType.resource,
        hexLocation: const HexLocation(1, -1),
        position: const Offset(0.65, 0.16),
        connectedNodeIds: ['exp_1_5'],
      ),
      WorldNode(
        id: 'exp_1_5',
        name: 'Path Found',
        description: 'Complete Stage 1',
        directive: 'The Trial: Choose a primary archetype to specialize in.',
        emoji: '🏆',
        targetedAttributes: [HabitAttribute.vitality, HabitAttribute.strength],
        xpBoosts: {HabitAttribute.vitality: 25, HabitAttribute.strength: 25},
        requiredLevel: 5,
        stage: 1,
        levelInStage: 5,
        archetype: 'explorer',
        primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
        type: NodeType.milestone,
        hexLocation: const HexLocation(0, -2),
        position: const Offset(0.5, 0.24),
        connectedNodeIds: ['exp_2_1'],
      ),
    ],
  );

  /// All archetype data including new structure
  static const Map<String, dynamic> allArchetypes = {
    'athlete': {
      'stageCount': 3,
      'levelsPerStage': 5,
    },
    'scholar': {
      'stageCount': 3,
      'levelsPerStage': 5,
    },
    'creator': {
      'stageCount': 3,
      'levelsPerStage': 5,
    },
    'stoic': {
      'stageCount': 3,
      'levelsPerStage': 5,
    },
    'zealot': {
      'stageCount': 3,
      'levelsPerStage': 5,
    },
    'explorer': {
      'stageCount': 3,
      'levelsPerStage': 5,
    },
  };

  /// Get archetype journey nodes for a given archetype key
  static List<WorldNode> getArchetypeJourney(String archetypeKey) {
    switch (archetypeKey.toLowerCase()) {
      case 'zealot':
        return ZealotArchetype.getNodes();
      default:
        // For other archetypes, return their existing map nodes
        final config = getMapForArchetype(
          UserArchetype.values.firstWhere(
            (e) => e.name == archetypeKey,
            orElse: () => UserArchetype.none,
          ),
        );
        return config.nodes;
    }
  }
}

// ============ ZEALOT ARCHETYPE: Complete 15-Level Journey ============

/// Zealot archetype - devotion and spiritual strength
/// 3 stages of 5 levels each following the standardized progression pattern
class ZealotArchetype {
    static const String archetypeKey = 'zealot';

    static List<WorldNode> getNodes() {
      return [
        // STAGE 1: SHRINE (Levels 1-5)
        WorldNode(
          id: 'zealot_1_1',
          name: 'First Flame',
          description: 'Light your first flame of devotion',
          directive: 'Begin your practice: Spend 10 minutes in prayer or meditation.',
          emoji: '🕯️',
          targetedAttributes: [HabitAttribute.spirit],
          xpBoosts: {HabitAttribute.spirit: 15},
          requiredLevel: 1,
          stage: 1,
          levelInStage: 1,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.waypoint,
          hexLocation: const HexLocation(0, 0),
          position: const Offset(0.5, 0.05),
          connectedNodeIds: ['zealot_1_2'],
          state: NodeState.available,
        ),
        WorldNode(
          id: 'zealot_1_2',
          name: 'Inner Fire',
          description: 'Complete 3 devotional habits',
          directive: 'Fuel the flame: Complete 3 habits that nurture your spirit today.',
          emoji: '🔥',
          targetedAttributes: [HabitAttribute.spirit],
          xpBoosts: {HabitAttribute.spirit: 20},
          requiredLevel: 2,
          stage: 1,
          levelInStage: 2,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.resource,
          hexLocation: const HexLocation(0, -1),
          position: const Offset(0.4, 0.12),
          connectedNodeIds: ['zealot_1_3'],
        ),
        WorldNode(
          id: 'zealot_1_3',
          name: 'Trial of Devotion',
          description: 'Maintain a 5-day streak and complete a strength workout',
          directive: 'Body and spirit: Complete a strength workout while maintaining your streak.',
          emoji: '⚔️',
          targetedAttributes: [HabitAttribute.spirit, HabitAttribute.strength],
          xpBoosts: {HabitAttribute.spirit: 20, HabitAttribute.strength: 15},
          requiredLevel: 3,
          stage: 1,
          levelInStage: 3,
          archetype: archetypeKey,
          primaryAttributes: ['spirit', 'strength'],
          type: NodeType.challenge,
          hexLocation: const HexLocation(-1, -1),
          position: const Offset(0.25, 0.18),
          connectedNodeIds: ['zealot_1_4'],
        ),
        WorldNode(
          id: 'zealot_1_4',
          name: 'Burning Focus',
          description: 'Practice morning ritual for 7 days',
          directive: 'Morning devotion: Establish a consistent morning practice for one week.',
          emoji: '🌅',
          targetedAttributes: [HabitAttribute.spirit, HabitAttribute.focus],
          xpBoosts: {HabitAttribute.spirit: 18, HabitAttribute.focus: 12},
          requiredLevel: 4,
          stage: 1,
          levelInStage: 4,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.resource,
          hexLocation: const HexLocation(1, -1),
          position: const Offset(0.65, 0.16),
          connectedNodeIds: ['zealot_1_5'],
        ),
        WorldNode(
          id: 'zealot_1_5',
          name: 'Flame Unleashed',
          description: 'Complete Stage 1 of the Zealot path',
          directive: 'The Trial: Complete a full day of perfect habit adherence.',
          emoji: '🔆',
          targetedAttributes: [
            HabitAttribute.strength,
            HabitAttribute.intellect,
            HabitAttribute.vitality,
            HabitAttribute.creativity,
            HabitAttribute.focus,
            HabitAttribute.spirit,
          ],
          xpBoosts: {
            HabitAttribute.spirit: 50,
            HabitAttribute.strength: 25,
            HabitAttribute.focus: 20,
          },
          requiredLevel: 5,
          stage: 1,
          levelInStage: 5,
          archetype: archetypeKey,
          primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
          type: NodeType.milestone,
          hexLocation: const HexLocation(0, -2),
          position: const Offset(0.5, 0.24),
          connectedNodeIds: ['zealot_2_1'],
        ),

        // STAGE 2: CONCLAVE (Levels 6-10)
        WorldNode(
          id: 'zealot_2_1',
          name: 'Conclave Entry',
          description: 'Enter the sacred gathering',
          directive: 'Community: Connect with others on a similar spiritual path.',
          emoji: '🕌',
          targetedAttributes: [HabitAttribute.spirit],
          xpBoosts: {HabitAttribute.spirit: 15},
          requiredLevel: 6,
          stage: 2,
          levelInStage: 1,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.waypoint,
          hexLocation: const HexLocation(0, -3),
          position: const Offset(0.5, 0.30),
          connectedNodeIds: ['zealot_2_2'],
        ),
        WorldNode(
          id: 'zealot_2_2',
          name: 'Devotional Chant',
          description: 'Complete 5 devotional habits in one week',
          directive: 'Sacred rhythm: Complete 5 spirit-nurturing activities this week.',
          emoji: '📿',
          targetedAttributes: [HabitAttribute.spirit],
          xpBoosts: {HabitAttribute.spirit: 25},
          requiredLevel: 7,
          stage: 2,
          levelInStage: 2,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.resource,
          hexLocation: const HexLocation(-1, -3),
          position: const Offset(0.3, 0.36),
          connectedNodeIds: ['zealot_2_3'],
        ),
        WorldNode(
          id: 'zealot_2_3',
          name: 'Trial of Faith',
          description: '10-day streak with strength and spirit habits',
          directive: 'Dual devotion: Maintain 10-day streak across spiritual and physical habits.',
          emoji: '⚡',
          targetedAttributes: [HabitAttribute.spirit, HabitAttribute.strength],
          xpBoosts: {HabitAttribute.spirit: 30, HabitAttribute.strength: 25},
          requiredLevel: 8,
          stage: 2,
          levelInStage: 3,
          archetype: archetypeKey,
          primaryAttributes: ['spirit', 'strength'],
          type: NodeType.challenge,
          hexLocation: const HexLocation(0, -4),
          position: const Offset(0.5, 0.38),
          connectedNodeIds: ['zealot_2_4'],
        ),
        WorldNode(
          id: 'zealot_2_4',
          name: 'Sacred Ritual',
          description: 'Establish a 14-day meditation practice',
          directive: 'Deep practice: Meditate for 20 minutes daily for two weeks.',
          emoji: '🧘',
          targetedAttributes: [HabitAttribute.spirit, HabitAttribute.focus],
          xpBoosts: {HabitAttribute.spirit: 35, HabitAttribute.focus: 20},
          requiredLevel: 9,
          stage: 2,
          levelInStage: 4,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.resource,
          hexLocation: const HexLocation(1, -3),
          position: const Offset(0.7, 0.36),
          connectedNodeIds: ['zealot_2_5'],
        ),
        WorldNode(
          id: 'zealot_2_5',
          name: 'Conclave Master',
          description: 'Complete Stage 2 of the Zealot path',
          directive: 'The Trial: Lead or guide someone in their spiritual practice.',
          emoji: '👑',
          targetedAttributes: [
            HabitAttribute.strength,
            HabitAttribute.intellect,
            HabitAttribute.vitality,
            HabitAttribute.creativity,
            HabitAttribute.focus,
            HabitAttribute.spirit,
          ],
          xpBoosts: {
            HabitAttribute.spirit: 60,
            HabitAttribute.strength: 30,
            HabitAttribute.focus: 25,
          },
          requiredLevel: 10,
          stage: 2,
          levelInStage: 5,
          archetype: archetypeKey,
          primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
          type: NodeType.milestone,
          hexLocation: const HexLocation(0, -5),
          position: const Offset(0.5, 0.45),
          connectedNodeIds: ['zealot_3_1'],
        ),

        // STAGE 3: ASCENSION (Levels 11-15)
        WorldNode(
          id: 'zealot_3_1',
          name: 'Ascension Begin',
          description: 'Begin your journey to transcendence',
          directive: 'Transcendence: Reflect on what truly matters to you.',
          emoji: '🌟',
          targetedAttributes: [HabitAttribute.spirit],
          xpBoosts: {HabitAttribute.spirit: 20},
          requiredLevel: 11,
          stage: 3,
          levelInStage: 1,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.waypoint,
          hexLocation: const HexLocation(0, -6),
          position: const Offset(0.5, 0.52),
          connectedNodeIds: ['zealot_3_2'],
        ),
        WorldNode(
          id: 'zealot_3_2',
          name: 'Divine Connection',
          description: '7 consecutive days of perfect habit adherence',
          directive: 'Pure devotion: 100% habit adherence for one full week.',
          emoji: '✨',
          targetedAttributes: [HabitAttribute.spirit, HabitAttribute.focus],
          xpBoosts: {HabitAttribute.spirit: 40, HabitAttribute.focus: 25},
          requiredLevel: 12,
          stage: 3,
          levelInStage: 2,
          archetype: archetypeKey,
          primaryAttributes: ['spirit', 'focus'],
          type: NodeType.resource,
          hexLocation: const HexLocation(-1, -6),
          position: const Offset(0.35, 0.58),
          connectedNodeIds: ['zealot_3_3'],
        ),
        WorldNode(
          id: 'zealot_3_3',
          name: 'Trial of Transcendence',
          description: '21-day streak with all spirit-based habits',
          directive: 'Ultimate test: 21-day streak on all spiritual practices.',
          emoji: '🔥',
          targetedAttributes: [HabitAttribute.spirit, HabitAttribute.strength, HabitAttribute.vitality],
          xpBoosts: {
            HabitAttribute.spirit: 50,
            HabitAttribute.strength: 30,
            HabitAttribute.vitality: 25,
          },
          requiredLevel: 13,
          stage: 3,
          levelInStage: 3,
          archetype: archetypeKey,
          primaryAttributes: ['spirit', 'strength', 'vitality'],
          type: NodeType.challenge,
          hexLocation: const HexLocation(0, -7),
          position: const Offset(0.5, 0.60),
          connectedNodeIds: ['zealot_3_4'],
        ),
        WorldNode(
          id: 'zealot_3_4',
          name: 'Eternal Flame',
          description: 'Maintain a 30-day devotion practice',
          directive: 'Lifelong commitment: 30 consecutive days of spiritual practice.',
          emoji: '🕯️',
          targetedAttributes: [HabitAttribute.spirit],
          xpBoosts: {HabitAttribute.spirit: 50},
          requiredLevel: 14,
          stage: 3,
          levelInStage: 4,
          archetype: archetypeKey,
          primaryAttributes: ['spirit'],
          type: NodeType.resource,
          hexLocation: const HexLocation(1, -6),
          position: const Offset(0.65, 0.58),
          connectedNodeIds: ['zealot_3_5'],
        ),
        WorldNode(
          id: 'zealot_3_5',
          name: 'Ascended',
          description: 'Complete Stage 3 - You have ascended!',
          directive: 'Ascension achieved: You have mastered the Zealot path.',
          emoji: '👼',
          targetedAttributes: [
            HabitAttribute.strength,
            HabitAttribute.intellect,
            HabitAttribute.vitality,
            HabitAttribute.creativity,
            HabitAttribute.focus,
            HabitAttribute.spirit,
          ],
          xpBoosts: {
            HabitAttribute.spirit: 100,
            HabitAttribute.strength: 50,
            HabitAttribute.focus: 40,
            HabitAttribute.intellect: 30,
            HabitAttribute.creativity: 30,
            HabitAttribute.vitality: 30,
          },
          requiredLevel: 15,
          stage: 3,
          levelInStage: 5,
          archetype: archetypeKey,
          primaryAttributes: ['strength', 'intellect', 'vitality', 'creativity', 'focus', 'spirit'],
          type: NodeType.milestone,
          hexLocation: const HexLocation(0, -8),
          position: const Offset(0.5, 0.68),
          connectedNodeIds: [],
        ),
      ];
    }

    /// Get visual theme for Zealot
    static Map<String, dynamic> getTheme() {
      return {
        'primaryColor': 0xFFFFAB00,
        'accentColor': 0xFFFFD54F,
        'background': 'flame_gradient',
        'particle': 'ember',
        'architecture': 'cathedral',
      };
    }
  }
